### ISSUE TITLE
Product purpose

### ISSUE THREAD

**Issue by rbodson1** [rbodson1/SWE-GraphicalPasswordAuthenticator#7]
write a comment of what you think the product purpose(s) is.

I will close the issue after everybody has commented.

**Comment by rbodson1** [comment]
I think the purpose of the product is to allow users to secure their apps (android) using graphical password. It creates sort of a fun scrambling game for the user to play, putting together the pieces of an image to recall the password.

**Comment by paladmer** [comment]
The primary purpose for using a graphical password as an authentication method would be to secure a user's private data. It decreases privacy breaches and keeps the user's data safe. It makes password guessing more difficult as it is more interactive and involved than a traditional alphanumerical password.

Additionally, it's been proven that people are more likely to remember visual images than words thus making a graphical authentication password method more user-friendly. (The Picture Superiority Effect is a phenomena in which visual images are more likely to be remembered than words.)


Source: Picture Superiority Effect , https://www.researchgate.net/publication/247213377_The_picture_superiority_effect_in_recognition_memory_A_developmental_study_using_the_response_signal_procedure

**Comment by kwamito92** [comment]
I think the purpose of this product is to make it easier for users to generate a password without the stress of overthinking. It removes the fault of users using one password for all their accounts and preventing data breaches. The human brain has a greater capability of remembering pictures than alphanumeric characters.  Also, the advantage of being user-friendly, higher security, and dictionary attack are less frequent. The biggest pro is being targeted by a hacker less difficult if can’t breach or guess your password.

**Comment by Jli421** [comment]
The purpose is to create an app that secures users' information better than the traditional password. This product uses graphical images instead of traditional textual information. Graphical passwords frequently require the user to select images in a particular order or respond to images presented in a particular order. This would make the app more secure.

**Comment by TearRinse** [comment]
The purpose of this application is to secure the users' information in a creative way that differs from the traditional password. It is less likely to be hacked as it would be more difficult to breach.

**Comment by Aaronportal465** [comment]
The purpose of this product would be to provide an alternative to text based passwords that is more convenient and easier for the user, but still maintains and can potentially even increase security due to the uniqueness each image could have per user. It would service to replace alphanumeric passwords with a pictorial solution to increase the security and uniqueness of a users password as well as making it more difficult for bots or other users. It adds more engagement by users being required to unscramble the image to solve the password and adds an aspect of puzzle solving and fun to the experience.
