### ISSUE TITLE
Target Users

### ISSUE THREAD

**Issue by rbodson1** [rbodson1/SWE-GraphicalPasswordAuthenticator#8]
write a comment of who you think the target user(s) should be.

I will close the issue after everybody has commented.

**Comment by rbodson1** [comment]
The target-users would be puzzle enthusiasts android-os phone users who want to put a security code (password) on their apps. Students, the elderly, receptionist (to kill time at work).

**Comment by kwamito92** [comment]
The target-users would be anyone with a smartphone and require a password. Students, Employees, artist, or puzzle enthusiast.

**Comment by TearRinse** [comment]
I agree the target users would be those who have an android phone and would want to use more of a puzzle-like password rather than a standard password

**Comment by Jli421** [comment]
First of all, the target users must be the ones who use Android devices, because this product is an Android app. Furthermore, the users must care about the security of the app, otherwise, they would not spend time searching for a new way to encode their passwords. Finally, the users must have stronger memorization of graphical information rather than texture information, otherwise, the traditional texture password would be more for them.

**Comment by paladmer** [comment]
Since about "85% of the total market share" are mobile android users, it makes sense to market our app towards those that use an Android phone. Our app will be catering towards those that know English since English is the third most universal and commonly known language. According to a study, Visual Working Memory peaks at around 20 so we would target the age range to be roughly 20-30. This is to ensure that the target audience has the capability to use our app. With these findings in mind, an individual that understands English and uses an android phone around the age of 20-30 would be the ideal candidate.

Additionally, businesses such as banks or game companies would benefit from our product as most of their users would like to secure their account. They  would want a higher level of security that an alphanumerical password could not provide. 

Source: 

https://appradar.com/blog/how-to-find-your-target-audience-for-mobile-apps  

https://mediakix.com/blog/android-statistics-facts-mobile-usage/   

https://websitebuilder.org/blog/app-usage-statistics/#:~:text=Consumers%20downloaded%20204%20billion%20apps,the%20most%20used%20app%20category.

https://www.businessinsider.com/smartest-age-for-everything-math-vocabulary-memory-2017-7#the-ability-to-learn-unfamiliar-names-peaks-at-22-2

https://www.ipac-traductions.com/en/blog/the-worlds-10-most-widely-spoken-languages/

These sources provide some backing as to why we would choose the specific target audience.

**Comment by Aaronportal465** [comment]
The primary usage of the "visual password" would likely be most smartphone users although PC users could potentially also use this feature if implemented. The password could be utilized to potentially replace user passwords across any of their online accounts much in the same way that captcha has become the standard to detect bots, and become a standard for a "visual password". It could easily become more popular than text based passwords due to the nature of it being easier to remember images as opposed to text, and many mobile users may prefer it.
